# Generated by Django 3.2.8 on 2021-12-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questlike',
            name='like',
            field=models.IntegerField(choices=[('pos', 1), ('neg', -1)], default=0),
        ),
    ]
