# Generated by Django 3.2.8 on 2021-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_questlike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questlike',
            name='like',
            field=models.IntegerField(choices=[(1, 'pos'), (-1, 'neg')], default=0),
        ),
    ]
