# Generated by Django 3.2.8 on 2021-12-29 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
